spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tanoak10/cloud-config.git
          username: 填写账户
          password: 填写密码
server:
  port: 1201
